[package]
name = "thiery-core"
version = "0.1.0-BETA"
edition = "2024"

[dependencies]
thiery-lib = { path = "../thiery-lib" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
color-eyre = "0.6"
